storeDir: ../.pnpm-store

minimumReleaseAgeExclude:
  - undici@7.29.1
  - js-yaml@3.15.2 || 4.3.2
  - brace-expansion@1.1.20
  - liquidjs@10.27.1
overrides:
  brace-expansion@>=1.0.0 <1.1.20: 1.1.20
  js-yaml@>=3.0.0 <3.15.2: 3.15.2
  js-yaml@>=4.0.0 <4.3.2: 4.3.2
  undici@>=7.0.0 <7.29.1: 7.29.1
